/* eslint-disable react-hooks/exhaustive-deps */
import "./globals.css";
import type { Metadata } from "next";
import "global";
import { Inter } from "next/font/google";

import { ScrollContext } from "@/context/AppProvider";

import MenuComponent from "@/components/MenuComponent/MenuComponent";
import { useDispatch, useSelector } from "react-redux";
import { RootState } from "@/redux";
import { setLanguage } from "@/redux/reducer/changeLanguageReducer/changeLanguage";
import { useEffect } from "react";
import RollTop from "@/components/RollTop";
import ChatRoll from "@/components/ChatRoll";

const inter = Inter({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // useEffect(() => {

  // }, []);
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <ScrollContext>
          <MenuComponent />
          {/* <div>nice</div> */}
          {children}
          <ChatRoll />
          <RollTop />
        </ScrollContext>
      </body>
    </html>
  );
}
